name: Metrics
on:
  # Schedule 00:00 GMT-6 == 12:00 GMT-6
  schedule: [{cron: "0 6,18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
  
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, languages
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: jupyter notebook, html, makefile
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          
      - name: Recent activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: recentActivity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 14

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendarFull.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_calendar: yes
          plugin_calendar_limit: 0
          
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: followupIndepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_followup: yes
          plugin_followup_indepth: yes
          
      - name: Opened on user's repositories
        uses: lowlighter/metrics@latest
        with:
          filename: followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_followup: yes
          
      - name: Opened by user
        uses: lowlighter/metrics@latest
        with:
          filename: followupUser.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: user
          
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: habitsFacts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: charlist
          config_timezone: America/Mexico_City
          
      - name: Repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: linesHistory.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 6
          plugin_lines_history_limit: 1
