name: 📖 Update README
on:
  # Schedule 00:00 GMT-6 == 12:00 GMT-6
  schedule:
   - cron: "0 6,18 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: 📊 Update 3D contribution graph
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: 📤 Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
  
  job2:
    name: 📐 Update metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 🌐 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_order: base.header, people
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_people: yes
          plugin_people_types: followers
          
      - name: 📅 Isocalendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: 🔠 Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: jupyter notebook, html, makefile
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_analysis_timeout: 60
          
      - name: 🌤️ GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: skyline.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          base: ""
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
          
      - name: 🌁 GitHub City
        uses: lowlighter/metrics@latest
        with:
          filename: skylineCity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          base: ""
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
          
      - name: 📌 Pinned repositories
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: pinnedRepositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          
      - name: 🎯 Projects
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_projects: yes
          plugin_projects_descriptions: yes

      - name: 🏆 Achievements compact
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievementsCompact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          
      - name: 🏅 Achievements detailed
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievementsDetailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: detailed
          
      - name: 🔮 Fortune
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: fortune.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_fortune: yes
          
      - name: 🆕 Recent activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: recentActivity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          
      - name: 🌟 Notable contributions
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: notableContributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      - name: 📆 Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendarFull.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_calendar: yes
          plugin_calendar_limit: 0
          
      - name: 🚩 Issues and pull requests opened on my repositories
        uses: lowlighter/metrics@latest
        with:
          filename: issuesAndPullRequestsOnMyRepositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_followup: yes
          plugin_followup_indepth: yes
          
      - name: 🐛 Issues and pull requests opened by me
        uses: lowlighter/metrics@latest
        with:
          filename: issuesAndPullRequestsByMe.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: user
          
      - name: 👨🏼‍💻 Coding habits
        uses: lowlighter/metrics@latest
        with:
          filename: habitsAndFacts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: charlist
          config_timezone: America/Mexico_City
          
      - name: 📤 Repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: linesHistory.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 6
          plugin_lines_history_limit: 1
          
      - name: ▶ Spotify recent
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyRecent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          
      - name: 🎲 Spotify random track form playlist
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyRandomTrack.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/6mjZMbWerfNjjqj2LuCJxV
          plugin_music_limit: 10
          
      - name: 🎵 Spotify top tracks last month
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopTracksLastMonth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_played_at: true
          
      - name: 🎶 Spotify top tracks last half year
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopTracksLastHalfYear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_played_at: true
          
      - name: 🕺🏼 Spotify top tracks all time
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopTracksAllTime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: long
          plugin_music_top_type: tracks
          plugin_music_played_at: true
          
      - name: 🎼 Spotify top artists last month
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopArtistsLastMonth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: short
          plugin_music_top_type: artists
          
      - name: 🎤 Spotify top artists last half year
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopArtistsLastHalfYear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: medium
          plugin_music_top_type: artists
          
      - name: 👨🏼‍🎤️ Spotify top artists all time
        uses: lowlighter/metrics@latest
        with:
          filename: spotifyTopArtistsAllTime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: aldodegollado
          plugin_music_mode: top
          plugin_music_token: ${{ secrets.METRICS_SPOTIFY_TOKENS }}
          plugin_music_limit: 20
          plugin_music_time_range: long
          plugin_music_top_type: artists
          
      - name: ⏰ Wakatime stats
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
  
  job3:
    name: 🐍 Update snake animation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: ⚙ Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: 📤 Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  job4:
    name: ❗ Update recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  job5:
    name: ⏰ Update WakaTime stats complete
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"

          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"

          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "True"
          LOCALE: "en"
    
